apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-rds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  rrds-endpoint.json: ICAgICAgICAgICAgRW5kcG9pbnQ6IHsKICAgICAgICAgICAgICAgIEFkZHJlc3M6IGRhdGFiYXNlLXRlc3Qtb3ppZWwwMy5jZXM1dGl3amhyYXYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tLAogICAgICAgICAgICAgICAgUG9ydDogMzMwNiwKICAgICAgICAgICAgICAgIEhvc3RlZFpvbmVJZDogWjJSMklUVUdQTTYxQU0KICAgICAgICAgICAgfSwK