apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-rds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  bucket: {{ .Release.Name | b64enc }}