apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rds-wait-available
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:  
    "helm.sh/hook": post-install
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "rds", "wait", "db-instance-available"]
          args: 
          - --db-instance-identifier
          - {{ .Release.Name }}-rds-mysql

          volumeMounts:
            - name: aws-cli-config
              mountPath: /root/.aws
      restartPolicy: Never
      volumes:
        - name: aws-cli-config