apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rds-delete
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:  
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "rds", "delete-db-instance"]
          args: 
          - --db-instance-identifier
          - {{ .Release.Name }}-rds-mysql
          - --skip-final-snapshot
          volumeMounts:
            - name: aws-cli-config
              mountPath: /root/.aws
      restartPolicy: Never
      volumes:
        - name: aws-cli-config
          # configMap:
          #   name:



